### ISSUE TITLE
virustotal.com Malware Results Concern

### ISSUE THREAD

**Issue by ribbybbir** [Tatakinov/ninix-kagari#1]
こんにちは、タタキノフ、

あなたが現在のninix-kagari亜種の開発者なのですね。修正は歓迎しますが、virustotal.comのレポートからわかるように、マルウェアとの関係や挙動に懸念があります。念のため、潜在的な災難に備えて詐欺アラートをお勧めします。https://www.virustotal.com/gui/file/c28d051552f1b29dc3e4b59cbb91070b0f4789aa69ac35e2dcf8a72ab8b02058/relations

---

Hello Tatakinov,

I see that you are the developer of the current ninix-kagari variant. While fixes are welcoming, I have concern about malware relations and behavior as indicated from the virustotal.com report. To be careful, I suggest fraud alert in case of potential mishaps. https://www.virustotal.com/gui/file/c28d051552f1b29dc3e4b59cbb91070b0f4789aa69ac35e2dcf8a72ab8b02058/relations

**Comment by Tatakinov** [comment]
The files in ninix-kagari.zip consist of the libraries installed with rubyinstaller, the libraries installed with gem, and ninix-kagari.
All ninix-kagari-related files are text-based and there is no risk of malware.
If there is any malware, it would be ruby ​​or gem, but
since they are all installed with rubyinstaller or gem, it is outside my jurisdiction.
If you are concerned, please report it there.
(By the way, the version of rubyinstaller is Ruby+Devkit 3.2.3-1(x86).)

Since it has not been fixed to date, I think it is a false positive, but since it concerns me, I intend to increase the Ruby version from the next release.

----

ninix-kagari.zip内のファイルについては、rubyinstallerでインストールしたライブラリ群とgemでインストールしたライブラリ群とninix-kagariで構成されています。
ninix-kagari関連のファイルはすべてテキストベースでマルウェアの恐れはありません。
あるとすればrubyかgemですが、
すべてrubyinstallerかgemでインストールされるもののため、私の管轄外です。
気になるようでしたらそちらへご報告願います。
(ちなみにrubyinstallerのバージョンはRuby+Devkit 3.2.3-1(x86)です。)

現在に至るまで修正されていないことからfalse positiveだとは思いますが、気になるので次のReleaseからはRubyのバージョンを上げるつもりです。
